spring.application.name=demo
spring.h2.console.enabled=true

# Descomente para usar o banco de dados H2 (em mem�ria) ao inv�s do MySQL
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.jpa.hibernate.ddl-auto=update

#Conex�o com o MySQL - Substitua dw2 na URL pelo nome do seu banco
spring.datasource.url=jdbc:mysql://localhost:3306/trabalho11?serverTimezone=UTC
spring.datasource.username=ppi
spring.datasource.password=Ca123024975636.

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# O Hibernate ir� criar as tabelas do MySQL automaticamente, caso n�o existam.
spring.jpa.hibernate.ddl-auto=update

# Exibe as instru��es SQL executadas no console (�til para depura��o)
spring.jpa.show-sql=true

# Mantem a conex�o com o banco aberta at� finalizar a requisi��o (view/JSON � gerado)
spring.jpa.open-in-view=true

